### ISSUE TITLE
google 6.2.0 missing

### ISSUE THREAD

**Issue by wyardley** [opentofu/registry#939]
I'm getting this error trying to use `hashicorp/google` provider v6.2.0.
```
│ Error: Failed to resolve provider packages
│ 
│ Could not resolve provider hashicorp/google: no available releases match
│ the given constraints >= 3.64.0, 6.2.0, < 7.0.0
```

While the file was updated at the same time for `google` and `google-beta`, google seems to have 6.1.0 and google-beta seems to have 6.2.0.

https://github.com/opentofu/registry/blob/2bec72c69531af7ea406df46e5ec6172fa6b2c6a/providers/h/hashicorp/google.json#L4

https://github.com/opentofu/registry/blob/2bec72c69531af7ea406df46e5ec6172fa6b2c6a/providers/h/hashicorp/google-beta.json#L4

### OpenTofu Version

```shell
OpenTofu v1.8.2
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/google v5.43.1
+ provider registry.opentofu.org/hashicorp/google-beta v5.43.1
```

### OpenTofu Configuration Files
```hcl
terraform {
  required_version = ">= 1.8.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "6.2.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "6.2.0"
    }
  }
}
```

Not sure if this is similar to #659?

**Comment by ghost** [comment]
Hey @wyardley thank you for reporting this, this is indeed the case, we are looking into it.

**Comment by Yantrio** [comment]
This is now resolved. We identified a small race condition and corner case in our updating process and manually resolved this for now. Thanks for bringing this to our attention!

6.20 should be available shortly. It was added in [this commit](https://github.com/opentofu/registry/commit/46833289ec57d2fc3abb5352994e6e801843ea47).

**Comment by wyardley** [comment]
8 hours later, still getting the same error, and still not seeing it in the registry
```
% curl -s https://registry.opentofu.org/v1/providers/hashicorp/google/versions | yq '.versions[0].version'  
6.1.0
% curl -s https://registry.opentofu.org/v1/providers/hashicorp/google/versions | grep 6\\.2\\.0
% 
```

```
2024-09-12T08:16:20.709-0700 [DEBUG] GET https://registry.opentofu.org/v1/providers/hashicorp/google/versions
2024-09-12T08:16:20.913-0700 [DEBUG] no available releases match the given constraints >= 3.64.0, 6.2.0, < 7.0.0
2024-09-12T08:16:20.913-0700 [DEBUG] Available releases: [0.1.0 0.1.1 0.1.2 0.1.3 1.0.0 1.0.1 1.1.0 1.1.1 1.2.0 1.3.0 1.4.0 1.5.0 1.6.0 1.7.0 1.8.0 1.9.0 1.10.0 1.11.0 1.12.0 1.13.0 1.14.0 1.15.0 1.16.0 1.16.1 1.16.2 1.17.0 1.17.1 1.18.0 1.19.0 1.19.1 1.20.0 2.0.0 2.1.0 2.2.0 2.3.0 2.4.0 2.4.1 2.5.0 2.5.1 2.6.0 2.7.0 2.8.0 2.9.0 2.9.1 2.10.0 2.11.0 2.12.0 2.13.0 2.14.0 2.15.0 2.16.0 2.17.0 2.18.0 2.18.1 2.19.0 2.20.0 2.20.1 2.20.2 2.20.3 3.0.0-beta.1 3.0.0 3.1.0 3.2.0 3.3.0 3.4.0 3.5.0 3.6.0 3.7.0 3.8.0 3.9.0 3.10.0 3.11.0 3.12.0 3.13.0 3.14.0 3.15.0 3.16.0 3.17.0 3.18.0 3.19.0 3.20.0 3.21.0 3.22.0 3.23.0 3.24.0 3.25.0 3.26.0 3.27.0 3.28.0 3.29.0 3.30.0 3.31.0 3.32.0 3.33.0 3.34.0 3.35.0 3.36.0 3.37.0 3.38.0 3.39.0 3.40.0 3.41.0 3.42.0 3.43.0 3.44.0 3.45.0 3.46.0 3.47.0 3.48.0 3.49.0 3.50.0 3.51.0 3.51.1 3.52.0 3.53.0 3.54.0 3.55.0 3.56.0 3.57.0 3.58.0 3.59.0 3.60.0 3.61.0 3.62.0 3.63.0 3.64.0 3.65.0 3.66.0 3.66.1 3.67.0 3.68.0 3.69.0 3.70.0 3.71.0 3.72.0 3.73.0 3.74.0 3.75.0 3.76.0 3.77.0 3.78.0 3.79.0 3.80.0 3.81.0 3.82.0 3.83.0 3.84.0 3.85.0 3.86.0 3.87.0 3.88.0 3.89.0 3.90.0 3.90.1 4.0.0 4.1.0 4.2.0 4.2.1 4.3.0 4.4.0 4.5.0 4.6.0 4.7.0 4.8.0 4.9.0 4.10.0 4.11.0 4.12.0 4.13.0 4.14.0 4.15.0 4.16.0 4.17.0 4.18.0 4.19.0 4.20.0 4.21.0 4.22.0 4.23.0 4.24.0 4.25.0 4.26.0 4.27.0 4.28.0 4.29.0 4.30.0 4.31.0 4.32.0 4.33.0 4.34.0 4.35.0 4.36.0 4.37.0 4.38.0 4.39.0 4.40.0 4.41.0 4.42.0 4.42.1 4.43.0 4.43.1 4.44.0 4.44.1 4.45.0 4.46.0 4.47.0 4.48.0 4.49.0 4.50.0 4.51.0 4.52.0 4.53.0 4.53.1 4.54.0 4.55.0 4.56.0 4.57.0 4.58.0 4.59.0 4.60.0 4.60.1 4.60.2 4.61.0 4.62.0 4.62.1 4.63.0 4.63.1 4.64.0 4.65.0 4.65.1 4.65.2 4.66.0 4.67.0 4.68.0 4.69.0 4.69.1 4.70.0 4.71.0 4.72.0 4.72.1 4.73.0 4.73.1 4.73.2 4.74.0 4.75.0 4.75.1 4.76.0 4.77.0 4.78.0 4.79.0 4.80.0 4.81.0 4.82.0 4.83.0 4.84.0 4.85.0 5.0.0 5.1.0 5.2.0 5.3.0 5.4.0 5.5.0 5.6.0 5.7.0 5.8.0 5.9.0 5.10.0 5.11.0 5.12.0 5.13.0 5.14.0 5.15.0 5.16.0 5.17.0 5.18.0 5.19.0 5.20.0 5.21.0 5.22.0 5.23.0 5.24.0 5.25.0 5.26.0 5.27.0 5.28.0 5.29.0 5.29.1 5.30.0 5.31.0 5.31.1 5.32.0 5.33.0 5.34.0 5.35.0 5.36.0 5.37.0 5.38.0 5.39.0 5.39.1 5.40.0 5.41.0 5.42.0 5.43.0 5.43.1 5.44.0 6.0.0 6.0.1 6.1.0]
- Using previously-installed hashicorp/google-beta v6.2.0
```

(oddly, in a state that has _both_ `google-beta` and `google`, I don't see the debugging output above with `TF_LOG=debug` set before `opentofu` dies with an error, but if I have `google` only, I'll see it)

**Comment by wyardley** [comment]
Could [these failures](https://github.com/opentofu/registry/actions/runs/10821698464) be related as well? (the `--max-delete threshold reached` errors)?

**Comment by ghost** [comment]
Reopening as it is not fixed.

**Comment by Yantrio** [comment]
Hi, Thanks for your patience on this one. By mistake I fixed the opentofu google provider but didn't fix the hashicorp one. Complete oversight on my part but this is now working. Thanks for your patience here.
